name: Flujo de trabajo para ejecutar los test
on:
  push:
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonando el repositorio y estableciendo el espacio de trabajo
        uses: actions/checkout@v3
      - name: Configurando java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '16'
      - name: Construyendo y probando el código
        id: pasoBuild
        run: |
          chmod +x gradlew        
          ./gradlew assemble
      - name: mensaje con el uvus
        run: echo "manmanher"
         
  Test:
   runs-on: ubuntu-latest
   needs: Build    
   steps:
      - name: Clonando el repositorio y estableciendo el espacio de trabajo
        uses: actions/checkout@v3
      - name: Configurando java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '16'
      - name: Ejecutando pruebas
        run: |
          chmod +x gradlew        
          ./gradlew test
      - name: mensaje con el uvus
        run: echo "manmanher"
 
